# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GdriveCli < Formula
  desc "CLI tool to search and download Google Docs, Sheets, and Slides"
  homepage "https://github.com/natikgadzhi/gdrive-cli"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.3.0/gdrive-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "65a511718a4d698afa0b0305ce0789bb3bd35f304173c39f9eb1657676b19c07"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.3.0/gdrive-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "0308b650a256596623803406941ec88bdb3c52a70c68be625e9f6bb76d0365a0"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.3.0/gdrive-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "7aa92ac5acf1c39d8daa80052676cb51aa4c1f040a3524d5ea71ced58f2cf463"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.3.0/gdrive-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "8715aac6f689be176aa642719bc398394918dcab7054208eacd7a47eb17a074e"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end
end
