# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GdriveCli < Formula
  desc "CLI tool to search and download Google Docs, Sheets, and Slides"
  homepage "https://github.com/natikgadzhi/gdrive-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.0.1/gdrive-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "37443654f9c3858441617b09626d77c33106bfe0bcb111331c174f1d113a6a54"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.0.1/gdrive-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "fc762bfc5f233260a1f54a7cf0a55dbf5c1d1398d7ef49a95dd99613fc88fb55"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.0.1/gdrive-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "d023dd64af61a17f22fe7753f8df33905a1313d60e0e5e251de2deb63d7ff1c8"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.0.1/gdrive-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "50e95cbec6c4fcb98e4f177d5bd0270cf3b909b0f662c6b95bdaa1987530399b"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end
end
