# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitbatch < Formula
  desc "Batch-update git repositories in parallel"
  homepage "https://github.com/natikgadzhi/gitbatch"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/gitbatch/releases/download/v0.4.0/gitbatch_0.4.0_darwin_amd64.tar.gz"
      sha256 "8e4e1da0a0fc9eecb6f129d6faef535eff1bc8cb80ef115e22fd1ee76bcbb96b"

      define_method(:install) do
        bin.install "gitbatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/gitbatch/releases/download/v0.4.0/gitbatch_0.4.0_darwin_arm64.tar.gz"
      sha256 "4e11299c2be955e1ae3be49b39590a546d0ca3619ce92f67f9d274724be0732a"

      define_method(:install) do
        bin.install "gitbatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gitbatch/releases/download/v0.4.0/gitbatch_0.4.0_linux_amd64.tar.gz"
      sha256 "9cb9380cb1ca01ad09d854e02ea708632625d3018f7f3e5bdcc904a658dc22a7"
      define_method(:install) do
        bin.install "gitbatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gitbatch/releases/download/v0.4.0/gitbatch_0.4.0_linux_arm64.tar.gz"
      sha256 "09a5c62f2af29e64e95fbc075ecb11212304377411c557019551823529a48585"
      define_method(:install) do
        bin.install "gitbatch"
      end
    end
  end

  test do
    system "#{bin}/gitbatch", "--help"
  end
end
