# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitbatch < Formula
  desc "Batch-update git repositories in parallel"
  homepage "https://github.com/natikgadzhi/gitbatch"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/gitbatch/releases/download/v0.2.0/gitbatch_0.2.0_darwin_amd64.tar.gz"
      sha256 "d64eeed6d0958075172e3710f31d60d99137f6f73c5a70926c7261eded9ff732"

      define_method(:install) do
        bin.install "gitbatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/gitbatch/releases/download/v0.2.0/gitbatch_0.2.0_darwin_arm64.tar.gz"
      sha256 "0b53219abb0ad7982bc5649a420414a11dc23ae1d7b78abff36a45b9677b11b8"

      define_method(:install) do
        bin.install "gitbatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gitbatch/releases/download/v0.2.0/gitbatch_0.2.0_linux_amd64.tar.gz"
      sha256 "a7470ab0727351f02e8e25f2b7ffa3df5c94321897d59650283772ea1442fafb"
      define_method(:install) do
        bin.install "gitbatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gitbatch/releases/download/v0.2.0/gitbatch_0.2.0_linux_arm64.tar.gz"
      sha256 "215efe1111fe9a4ef199ea7d16313d69a16069a46f8366f942180459efcc477f"
      define_method(:install) do
        bin.install "gitbatch"
      end
    end
  end

  test do
    system "#{bin}/gitbatch", "--help"
  end
end
